### ISSUE TITLE
Non quantified variables

### ISSUE THREAD

**Issue by hharryyf** [javier-romero/qasp#5]
Hi, I'm a bit confused on how you are dealing with non-quantified variables. For example, in the following program, how are you quantifying p and q? Are they quantified in the inner-most quantified block existentially or the outer-most quantifier block existentially or you just ignore both variables and all the rules related to them? Thanks.
`_exists(1, x).
_forall(2, r).
{x;r;p;q}.
x :- r.
p :- q.
q.`

**Comment by javier-romero** [comment]
Hi, they are quantified in the inner-most quantified block existentially. That program is essentially the same as this one:
```
 _exists(1, x). _forall(2, r). {x;r;p;q}. x :- r. p :- q. q.
 _exists(3, p). _exists(3, q).
 ```
 Note that this agrees with the informal definition given on the README, and with the formal definition of the paper that is linked from there.
